name: Build, Test, and Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build-and-test:
    name: Lint, Build, and Test(Unit & Integration)    
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Output the commits
          run: |
            echo "Commits: ${{ github.event.before }}...${{ github.sha }}"


